/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_NdkJniUtils */

#ifndef _Included_com_test_NdkJniUtils
#define _Included_com_test_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_NdkJniUtils
 * Method:    getStringFormJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_NdkJniUtils_getStringFormJNI  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
